main/api/urls.py
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from main.api import (
    views,
    views_gitsvn,
    views_health,
    views_home,
    views_movieflex,
    views_system,
    views_tasks,
)

app_name = "api"

# newly registered ViewSet
router = routers.DefaultRouter()
router.register(r"project", viewset=views_gitsvn.ProjectDetailAPI, basename="project")

router.register(r"health/rule", viewset=views_health.RuleAPI, basename="rule")
router.register(r"health/dt", viewset=views_health.DailyActivityViewset, basename="dt")
router.register(
    r"trigger/health/daily",
    viewset=views_health.TriggerHealth,
    basename="trigger-health",
)

router.register(
    r"movieflex/movie", viewset=views_movieflex.MediaViewset, basename="movie"
)
router.register(
    r"movieflex/watching", viewset=views_movieflex.WatchingViewset, basename="watching"
)
router.register(
    r"movieflex/anime",
    viewset=views_movieflex.WebScrappingViewset,
    basename="movieflex-anime",
)

router.register(r"celery/tasks", viewset=views.TaskResultViewset, basename="tasks")

router.register(r"tasks/todo", viewset=views_tasks.TodoViewset, basename="todo")

router.register(r"home/epl", viewset=views_home.EPLListing, basename="home-epl")

router.register(
    r"system/sp",
    viewset=views_system.SystemPropertyViewset,
    basename="system-systemproperty",
)


urlpatterns = [
    path("", include(router.urls)),
    path("api-auth", include("rest_framework.urls", namespace="rest_framework")),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "docs",
        SpectacularSwaggerView.as_view(
            # template_name="swagger-ui.html",
            url_name="api:schema"
        ),
        name="swagger-ui",
    ),
    path(
        route="weather",
        view=views.OpenWeatherAPI.as_view(),
        name="openweather_list_view",
    ),
    path(
        route="ip",
        view=views_home.IpifyAPI.as_view(),
        name="ipify_list_view",
    ),
]

main/gitsvn/urls.py
from django.urls import path

from main.gitsvn import views

app_name = "git"

urlpatterns = [
    path(
        route="",
        view=views.GitHomeView.as_view(),
        name="git_list_view",
    ),
    path(
        route="project/<pk>/",
        view=views.GitProjectDetail.as_view(),
        name="git_detail_view",
    ),
]

main/health/urls.py
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.urls import path
from django.views.decorators.cache import cache_page

from main.health import views

CACHE_TTL = getattr(settings, "CACHE_TTL", DEFAULT_TIMEOUT)

app_name = "health"

urlpatterns = [
    path(
        route="",
        view=cache_page(CACHE_TTL)(views.HealthHomeView.as_view()),
        name="health_list_view",
    ),
    path(
        route="rule/create",
        view=views.RuleCreateView.as_view(),
        name="rule_create_view",
    ),
    path(
        route="rule/json",
        view=views.JSONView.as_view(),
        name="rule_json_view",
    ),
]

main/home/urls.py
from django.urls import path

from main.home import views

app_name = "home"

urlpatterns = [
    path("login", views.UserLoginView.as_view(), name="login"),
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home_list_view",
    ),
    path(
        route="profile",
        view=views.ProfileView.as_view(),
        name="profile_list_view",
    ),
    path(
        route="home/fifa",
        view=views.FifaView.as_view(),
        name="fifa_list_view",
    ),
]

rotary_phone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),  # authentication
    path("accounts/", include("django.contrib.auth.urls")),  # authentication
    path("", include("main.home.urls")),
    path("api/", include("main.api.urls")),
    path("git/", include("main.gitsvn.urls")),
    path("health/", include("main.health.urls")),
    path("system/", include("main.system.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dist/img/favicon_io/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'dist/img/favicon_io/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dist/img/favicon_io/favicon-16x16.png' %}">

  <title>{% block title %}Rotary Phone{% endblock %}</title>

  {% include 'base/css.html' %}

  {% block css %}{% endblock css %}

</head>

<body>

  {% comment %} {% include 'base/headers.html' %} {% endcomment %}
  {% include 'base/navbar.html' %}
  {% include 'base/sidebar.html' %}
  {% include 'base/logging.html' %}

  <div class="container-fluid">
    <div class="preloader" id="loading"></div>

    <div class="row">
      <!-- <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4"> -->
        <main class="col-md-12 ms-sm-auto col-lg-12 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2 text-secondary">{% block headers %}{% endblock headers %}</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            {% block headerbuttons %}{% endblock headerbuttons %}
          </div>
        </div>
        {% block content %}{% endblock content %}
      </main>
    </div>

  </div>

  {% include 'base/js.html' %}

  {% block js %}{% endblock js %}

  <script>
    // var ul = document.querySelector("header>.container>div>ul");
    // ul.addEventListener('click', (e) => {
    //   const et = e.target;
    //   e.preventDefault();
    //   const active = document.querySelector(".link-secondary");
    //   if (active) {
    //     active.classList.remove("link-secondary");
    //     active.classList.add("link-dark");
    //   }
    //   // add active class to the clicked element
    //   et.classList.remove("link-dark");
    //   et.classList.add("link-secondary");
    // })
  </script>
</body>

</html>

templates/base/css.html
{% load static %}

<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'dist/assets/css/fontawesome/css/all.min.css' %}">

<!-- Google Fonts -->
<!-- link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&family=Open+Sans&family=Roboto&family=Roboto+Mono&display=swap" rel="stylesheet" -->
<link rel="stylesheet" href="{% static 'dist/assets/fonts/fonts.css' %}">

<link rel="stylesheet" href="{% static 'dist/assets/css/bootstrap.min.css' %}">

<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

<!-- Datatables -->
<link rel="stylesheet" type="text/css"
href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.4/r-2.2.9/datatables.min.css" />

<link rel="stylesheet" href="{% static 'dist/base.css' %}">

<link rel="stylesheet" href="{% static 'dist/styles.css' %}">

<link rel="stylesheet" href="{% static 'dist/assets/css/navbar-top-fixed.css' %}">

<link rel="stylesheet" href="{% static 'dist/assets/css/list-groups.css' %}">

templates/base/headers.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Rotary Phone</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<!--
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
-->
</header>

templates/base/js.html
{% load static %}


<!-- jQuery -->
<script src="{% static 'dist/assets/js/jquery.min.js' %}" type="application/javascript"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.4/r-2.2.9/datatables.min.js"
  type="application/javascript">
</script>

<!-- Bootstrap -->
<script src="{% static 'dist/assets/js/bootstrap.bundle.js' %}" type="application/javascript"></script>
<!-- Index -->
<script src="{% static 'dist/index.js' %}" type="application/javascript"></script>

templates/base/logging.html
{% load static %}

  <div class="toast-container end-0 p-3 position-fixed" style="top: 10%; z-index: 5;"></div>

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %} id="alertID">

  <strong>{{ message.tags|capfirst }}!</strong> {{ message|safe }}
  <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>

</div>
{% endfor %}
{% endif %}

templates/base/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
  <div class="container-fluid">
    {% comment %} <a class="navbar-brand" href="{% url 'home:home_list_view' %}">
      <img src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24"
        class="d-inline-block align-text-top">
      ...</a> {% endcomment %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-white" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"><i
              class="fa-solid fa-house"></i> Home</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'home:home_list_view' %}"><i
                  class="bi bi-journals"></i> Dashboard</a></li>
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'home:fifa_list_view' %}"><i
                    class="bi bi-journals"></i> FIFA</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown text-decoration-none">
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"
            ><i class="fa-brands fa-git"></i> Git</a>
          <ul class="dropdown-menu dropdown-menu-start mx-0 shadow w-220px">
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'git:git_list_view' %}"><i
                  class="fa-brands fa-git"></i> Projects</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'logout' %}"><i
                  class="bi bi-box-arrow-right"></i> TBD</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown text-decoration-none">
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"
            ><i class="fa-solid fa-heart-pulse"></i> Health</a>
          <ul class="dropdown-menu dropdown-menu-start mx-0 shadow w-220px">
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'health:health_list_view' %}"><i
                  class="fa-solid fa-heart-pulse"></i> Health</a></li>
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="#" onclick="javascript:health.triggerFetch('/api/trigger/health/daily/', 'POST')">Trigger Daily</a></li>
          </ul>

        </li>

        <li class="nav-item dropdown text-decoration-none">
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"
            ><i class="nav-icon fas fa-archway"></i> System</a>
          <ul class="dropdown-menu dropdown-menu-start mx-0 shadow w-220px">
            <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'system:system_home' %}"><i
                  class="fa-solid fa-heart-pulse"></i> System</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown text-decoration-none">
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"
            ><i class="nav-icon fas fa-archway"></i> Pages</a>
          <ul class="dropdown-menu dropdown-menu-start mx-0 shadow w-220px">
            <li><a class="dropdown-item d-flex gap-2 align-items-center"  target="_blank" href="http://localhost:8080/"><i
                  class="fa-solid fa-heart-pulse"></i> pgAdmin4</a></li>
          </ul>
        </li>


      </ul>
      <a class="nav-item text-bg-dark text-decoration-none text-white" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions"
        aria-controls="offcanvasWithBothOptions" >
        <i class="fa-solid fa-bars"></i></a>

      <li class="d-flex nav-item dropdown text-decoration-none">
        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown" aria-expanded="false"
          >{{request.user.get_full_name}}</a>
        <ul class="dropdown-menu dropdown-menu-end mx-0 shadow w-220px">
          <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'admin:index' %}"><i
                class="fa-solid fa-user-doctor"></i> Admin</a></li>
          <li><a class="dropdown-item d-flex gap-2 align-items-center" target="_blank" href="{% url 'api:swagger-ui' %}"><i
                class="fa-solid fa-tape"></i> Api</a></li>
          <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'home:profile_list_view' %}"><i
                class="bi bi-person"></i> Profile</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item d-flex gap-2 align-items-center" href="{% url 'logout' %}"><i
                class="bi bi-box-arrow-right"></i> Logout</a></li>
        </ul>
      </li>

    </div>

  </div>
</nav>

templates/base/sidebar.html
<div class="offcanvas offcanvas-end text-white navbar-dark" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
  aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Rotary Phone</h5>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <hr>
  <div class="offcanvas-body">
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
      <li class="nav-item">
        <a href="#" class="nav-link text-truncate text-white">
          <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
        </a>
      </li>
      <li>
        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link text-truncate text-white">
          <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
      </li>
      <li>
        <a href="#" class="nav-link text-truncate text-white">
          <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Orders</span></a>
      </li>
      <li class="dropdown">
        <a href="#" class="nav-link dropdown-toggle text-truncate text-white" id="dropdown" data-bs-toggle="dropdown"
          aria-expanded="false">
          <i class="fs-5 bi-bootstrap"></i><span class="ms-1 d-none d-sm-inline">Bootstrap</span>
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
          <li><a class="dropdown-item" href="#">New project...</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
      </li>
      <li>
        <a href="#" class="nav-link text-truncate text-white">
          <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Products</span></a>
      </li>
      <li>
        <a href="#" class="nav-link text-truncate text-white">
          <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Customers</span> </a>
      </li>
    </ul>

  </div>
</div>