main/api/urls.py
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from main.api import (
    views,
    views_gitsvn,
    views_health,
    views_home,
    views_movieflex,
    views_system,
    views_tasks,
)

app_name = "api"

# newly registered ViewSet
router = routers.DefaultRouter()
router.register(r"project", viewset=views_gitsvn.ProjectDetailAPI, basename="project")

router.register(r"health/rule", viewset=views_health.RuleAPI, basename="rule")
router.register(r"health/dt", viewset=views_health.DailyActivityViewset, basename="dt")
router.register(
    r"trigger/health/daily",
    viewset=views_health.TriggerHealth,
    basename="trigger-health",
)

router.register(
    r"movieflex/movie", viewset=views_movieflex.MediaViewset, basename="movie"
)
router.register(
    r"movieflex/watching", viewset=views_movieflex.WatchingViewset, basename="watching"
)
router.register(
    r"movieflex/anime",
    viewset=views_movieflex.WebScrappingViewset,
    basename="movieflex-anime",
)

router.register(r"celery/tasks", viewset=views.TaskResultViewset, basename="tasks")

router.register(r"tasks/todo", viewset=views_tasks.TodoViewset, basename="todo")

router.register(r"home/epl", viewset=views_home.EPLListing, basename="home-epl")

router.register(
    r"system/sp",
    viewset=views_system.SystemPropertyViewset,
    basename="system-systemproperty",
)


urlpatterns = [
    path("", include(router.urls)),
    path("api-auth", include("rest_framework.urls", namespace="rest_framework")),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "docs",
        SpectacularSwaggerView.as_view(
            # template_name="swagger-ui.html",
            url_name="api:schema"
        ),
        name="swagger-ui",
    ),
    path(
        route="weather",
        view=views.OpenWeatherAPI.as_view(),
        name="openweather_list_view",
    ),
    path(
        route="ip",
        view=views_home.IpifyAPI.as_view(),
        name="ipify_list_view",
    ),
]

main/health/urls.py
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.urls import path
from django.views.decorators.cache import cache_page

from main.health import views

CACHE_TTL = getattr(settings, "CACHE_TTL", DEFAULT_TIMEOUT)

app_name = "health"

urlpatterns = [
    path(
        route="",
        view=cache_page(CACHE_TTL)(views.HealthHomeView.as_view()),
        name="health_list_view",
    ),
    path(
        route="rule/create",
        view=views.RuleCreateView.as_view(),
        name="rule_create_view",
    ),
    path(
        route="rule/json",
        view=views.JSONView.as_view(),
        name="rule_json_view",
    ),
]

main/home/urls.py
from django.urls import path

from main.home import views

app_name = "home"

urlpatterns = [
    path("login", views.UserLoginView.as_view(), name="login"),
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home_list_view",
    ),
    path(
        route="profile",
        view=views.ProfileView.as_view(),
        name="profile_list_view",
    ),
    path(
        route="home/fifa",
        view=views.FifaView.as_view(),
        name="fifa_list_view",
    ),
]

rotary_phone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),  # authentication
    path("accounts/", include("django.contrib.auth.urls")),  # authentication
    path("", include("main.home.urls")),
    path("api/", include("main.api.urls")),
    path("git/", include("main.gitsvn.urls")),
    path("health/", include("main.health.urls")),
    path("system/", include("main.system.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone as tz
from django.utils.translation import gettext_lazy as _
import uuid

from main.utility.mixins import (
    ActiveStatusMixin,
    PrimaryIdMixin,
    StatusMixin,
    TimestampMixin,
    UUIDMixin,
)


class User(AbstractUser):

    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile_picture = models.ImageField(null=True, blank=True, default="default.jpg")
    bio = models.TextField(blank=True)
    headline = models.CharField(max_length=300)
    following = models.IntegerField(default=0)
    followers = models.IntegerField(default=0)
    friends = models.IntegerField(default=0)
    articles = models.IntegerField(default=0)
    # profile_picture = models.URLField(blank=True)
    date_of_birth = models.DateField(default="1990-01-01")
    is_admin = models.BooleanField(default=False)
    last_modified = models.DateTimeField(
        default=tz.now,
        verbose_name="Blog updated on",
        help_text="Updated Timestamp",
    )
    address = models.CharField(max_length=300, null=True)
    address_2 = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=300, null=True)
    state = models.CharField(max_length=300, null=True)
    country = models.CharField(max_length=300, null=True)
    zip = models.CharField(max_length=300, null=True)
    skills = models.JSONField(_("Skills"), default=dict)
    notes = models.TextField(_("Notes"))
    education = models.JSONField(_("Education"), default=dict)


class Audit(PrimaryIdMixin, TimestampMixin, UUIDMixin, StatusMixin):
    message = models.CharField(
        max_length=1000,
        verbose_name="Message",
        help_text="message",
    )
    task_id = models.CharField(_("Task Id"), blank=True, null=True, max_length=50)
    celery_task_id = models.CharField(
        _("Celery Task Id"), blank=True, null=True, max_length=50
    )

    class Meta:
        ordering = ["-id"]
        verbose_name_plural = "Audit"

    def __str__(self) -> str:
        return "| ".join([str(self.id), str(self.message)])


class Category(PrimaryIdMixin, TimestampMixin, ActiveStatusMixin):
    category = models.CharField(
        max_length=250,
        verbose_name="Category",
        help_text="Category",
    )
    sub_category = models.CharField(
        max_length=250,
        verbose_name="Category",
        help_text="Category",
    )

    class Meta:
        unique_together = ["category", "sub_category"]
        ordering = ["-id"]

    def __str__(self) -> str:
        return "| ".join([str(self.category), str(self.sub_category)])


class ActionList(PrimaryIdMixin, ActiveStatusMixin, TimestampMixin):
    name = models.CharField(_("name"), max_length=50)
    action = models.CharField(_("Action list"), max_length=250)

    class Meta:
        unique_together = ["name", "action"]
        ordering = ["-name"]

    def __str__(self) -> str:
        return "| ".join([str(self.name), str(self.action)])


class ActionLog(PrimaryIdMixin, ActiveStatusMixin, TimestampMixin):
    action_id = models.ForeignKey(
        to="home.ActionList",
        to_field="id",
        verbose_name=_("Action id"),
        on_delete=models.DO_NOTHING,
        related_name="actions",
    )
    status = models.CharField(_("status"), max_length=50, default="PENDING")
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=False)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return "| ".join([str(self.action_id), str(self.status)])

main/home/forms.py
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import BooleanField, CharField, CheckboxInput, TextInput


class CustomUserAuthenticationForm(AuthenticationForm):
    username = CharField(
        widget=TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "id": "floatingInput",
                "placeholder": "username",
                "name": "floatingInput",
            },
        ),
        label="",
    )
    password = CharField(
        widget=TextInput(
            attrs={
                "type": "password",
                "class": "form-control",
                "id": "floatingInput",
                "placeholder": "password",
                "name": "floatingInput",
            },
        ),
        label="",
    )
    remember_me = BooleanField(
        required=False,
        label="remember me",
        widget=CheckboxInput(
            attrs={
                "type": "checkbox",
                "class": "form-check-input",
                "id": "floatingCheckBox",
                "name": "floatingCheckBox",
            },
        ),
    )

    class Meta:
        model = User
        fields = ["username", "content", "password1", "password2", "remember_me"]

    def __init__(self, request, *args, **kwargs) -> None:
        super().__init__(request, *args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs = {"novalidate": ""}
        self.helper.form_method = "post"  # get or post method
        self.helper.form_class = "row row-cols-lg-auto g-3 align-items-center"

main/home/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from main.home.forms import CustomUserAuthenticationForm


class UserLoginView(LoginView):
    form_class = CustomUserAuthenticationForm
    authentication_form = CustomUserAuthenticationForm

    def form_valid(self, form):
        remember_me = form.cleaned_data["remember_me"]
        login(self.request, form.get_user())

        if remember_me:
            self.request.session.set_expiry(1209600)
        return super(LoginView, self).form_valid(form)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pending_review"] = 10
        context["open_tasks"] = 5
        context["unread_articles"] = 700
        context["budget_remaining"] = 200
        context["budget_consumed"] = "100,000.00"
        context["current_ip"] = "172.19.166.98"
        context["international_space_station"] = "-26.9884, -38.6396"
        context["temperature"] = "-26.9884"
        return context


class UserLogout(LogoutView):
    next_page = settings.LOGOUT_REDIRECT_URL


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "profile.html"


class FifaView(LoginRequiredMixin, TemplateView):
    template_name = "fifa.html"

main/home/templates/fifa.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ block.super }} - FIFA{% endblock title %}


{% block headers %}FIFA{% endblock headers %}

{% block headerbuttons %}

<div class="dropdown">
  <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Rules
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'health:rule_create_view' %}">Create</a></li>
    <li><a class="dropdown-item" href="#" onclick="javascript:health.triggerFetch('/api/trigger/health/daily/', 'POST')">Trigger Daily</a></li>
  </ul>
</div>

{% endblock headerbuttons %}

{% block content %}

  {% include 'fifa/epl_list.html' %}

{% endblock content %}

{% block js %}

  <script src="{% static 'dist/js/pages/home/fifa.js' %}" defer type="application/javascript"></script>

{% endblock js %}

main/home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ block.super }} - Home{% endblock title %}

{% block css %}

<style>
  .card {
    box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px;
    padding: 2px;
    border-radius: 4px;
    background: #fff;
    box-shadow: 0 6px 10px rgba(0, 0, 0, .08), 0 0 6px rgba(0, 0, 0, .05);
    transition: .3s transform cubic-bezier(.155, 1.105, .295, 1.12), .3s box-shadow, .3s -webkit-transform cubic-bezier(.155, 1.105, .295, 1.12);
    /* padding: 14px 80px 18px 36px; */
    cursor: pointer;
    /* width: 10rem; */
    /* height: 10rem; */
    margin: 0.5rem;
  }

  /* .card:hover {
    transform: translateY(-20px);
    transition: 0.1s ease-out;
    transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
  } */
</style>

<link rel="stylesheet" href="{% static 'pages/home/home.css' %}">

{% endblock css %}

{% block headers %}Dashboard{% endblock headers %}

{% block headerbuttons %}{% endblock headerbuttons %}

{% block content %}

<div class="row">

  <div class="col-lg-12 col-12">
    <div class="card">
      <div class="card-header fs-toggle" data-bs-toggle="collapse" data-bs-target="#refreshDashboard">
        <div class="row">
          <div class="col-md-12 bg-light text-right">
            <button type="button" class="btn btn-link float-end"
              data-bs-target="#refreshDashboard" aria-expanded="false" aria-controls="refreshDashboard"
              style="text-decoration: none; border: 1px dashed #61affe; ">
              <i class="bi bi-arrows-expand"></i>
            </button>
            <button type="button" class="btn btn-link float-end" data-bs-target="#refreshDashboard"
              aria-expanded="false" aria-controls="refreshDashboard" onclick="javascript:start.refreshDashboard();"
              style="text-decoration: none; border: 1px dashed #61affe;">
              <i class="bi bi-arrow-clockwise"></i>
            </button>
            <h3 class="float-start">Dashboard</h3>
          </div>
        </div>
      </div>
      <div class="collapse collapse-horizontal" id="refreshDashboard">
        <div class="card-body">
          <div class="row">

            {% include 'dashboard/widgets/current_temperature.html' with temperature=temperature %}

            {% include 'dashboard/widgets/pending_review.html' with pending_reviewopen_tasksunread_articles=pending_review %}

            {% include 'dashboard/widgets/open_rules.html' with open_tasksunread_articles=open_tasksunread_articles %}

            {% include 'dashboard/widgets/unread_articles.html' with unread_articles=unread_articles %}

            {% include 'dashboard/widgets/current_ip.html' with budget_remaining=budget_remaining %}

            {% include 'dashboard/widgets/budget_remaining.html' with budget_consumed=budget_consumed %}

            {% include 'dashboard/widgets/budget_consumed.html' with current_ip=current_ip %}

            {% include 'dashboard/widgets/international_space_station.html' with location=international_space_station %}
          </div>

          <div class="row">
            {% include 'dashboard/widgets/timer.html' %}
          </div>

        </div>
      </div>
    </div>
  </div>


</div>

<div class="b-divider"></div>

<div class="row">
  {% comment %} {% include 'dashboard/widgets/todo.html' %} {% endcomment %}
</div>

<div class="row">
  {% include 'dashboard/sections/rules.html' %}
</div>

<div class="b-divider"></div>
<div class="row">
  {% include 'dashboard/sections/list_projects.html' %}
</div>

<div class="b-divider"></div>
<div class="row">
  {% include 'dashboard/sections/users.html' %}
</div>

<div class="b-divider"></div>
<div class="row">
  {% include 'dashboard/sections/tasks.html' %}
</div>

<div class="b-divider"></div>
<div class="row">
  {% include 'dashboard/sections/movieflex.html' %}
</div>

<div class="b-divider"></div>


{% endblock content %}

{% block js %}

<script type=text/javascript>
  var BASE_API_IP = "{% url 'api:ipify_list_view' %}"

</script>

<script src="{% static 'pages/home/home.js' %}" type="application/javascript" defer></script>

{% endblock js %}

main/home/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}{{ block.super }} - Profile{% endblock title %}

{% block css %}

<style>
  .list-group {
    max-width: 460px;
    margin: 4rem auto;
  }

  .form-check-input:checked+.form-checked-content {
    opacity: .5;
  }

  .form-check-input-placeholder {
    border-style: dashed;
  }

  [contenteditable]:focus {
    outline: 0;
  }

  .list-group-checkable .list-group-item {
    cursor: pointer;
  }

  .list-group-item-check {
    position: absolute;
    clip: rect(0, 0, 0, 0);
  }

  .list-group-item-check:hover+.list-group-item {
    background-color: var(--bs-light);
  }

  .list-group-item-check:checked+.list-group-item {
    color: #fff;
    background-color: var(--bs-blue);
  }

  .list-group-item-check[disabled]+.list-group-item,
  .list-group-item-check:disabled+.list-group-item {
    pointer-events: none;
    filter: none;
    opacity: .5;
  }

  .list-group-radio .list-group-item {
    cursor: pointer;
    border-radius: .5rem;
  }

  .list-group-radio .form-check-input {
    z-index: 2;
    margin-top: -.5em;
  }

  .list-group-radio .list-group-item:hover,
  .list-group-radio .list-group-item:focus {
    background-color: var(--bs-light);
  }

  .list-group-radio .form-check-input:checked+.list-group-item {
    background-color: var(--bs-body);
    border-color: var(--bs-blue);
    box-shadow: 0 0 0 2px var(--bs-blue);
  }

  .list-group-radio .form-check-input[disabled]+.list-group-item,
  .list-group-radio .form-check-input:disabled+.list-group-item {
    pointer-events: none;
    filter: none;
    opacity: .5;
  }
</style>


{% endblock css %}

{% block headers %}Profile{% endblock headers %}

{% block headerbuttons %}{% endblock headerbuttons %}

{% block content %}

<div class="row">
  <div class="col-md-3">

    <!-- Profile Image -->
    <div class="card card-primary card-outline text-dark">
      <div class="card-body box-profile">
        <div class="text-center">
          <img class="profile-user-img img-fluid img-circle" src="{{ request.user.profile_picture.url }}"
            alt="User profile picture">
        </div>

        <h3 class="profile-username text-center">{{ user.get_full_name | safe | capfirst }}</h3>

        <p class="text-muted text-center">Software Engineer</p>

        <ul class="list-group w-auto">
          <li class="list-group-item">
            <b>Followers</b> <a class="float-right">{{ user.followers }}</a>
          </li>
          <li class="list-group-item">
            <b>Following</b> <a class="float-right">{{ user.following }}</a>
          </li>
          <li class="list-group-item">
            <b>Friends</b> <a class="float-right">{{ user.friends }}</a>
          </li>
        </ul>
      </div>
    </div>

    <!-- About Me Box -->
    <div class="card card-primary card-outline text-dark">
      <div class="card-header">
        <h3 class="card-title">About Me</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <strong><i class="fas fa-book mr-1"></i> Education</strong>

        <p class="text-muted">
          B.S. in Computer Science from the University of Tennessee at Knoxville
        </p>

        <hr>

        <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

        <p class="text-muted">Malibu, California</p>

        <hr>

        <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

        <p class="text-muted">
          <span class="tag tag-danger">UI Design</span>
          <span class="tag tag-success">Coding</span>
          <span class="tag tag-info">Javascript</span>
          <span class="tag tag-warning">PHP</span>
          <span class="tag tag-primary">Node.js</span>
        </p>

        <hr>

        <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim
          neque.</p>
      </div>
      <!-- /.card-body -->
    </div>
  </div>

  <div class="col-md-9">
    <div class="card card-primary card-outline text-dark">
      <div class="card-header p-2">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">

            <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile"
              type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
            <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
              type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</button>
            <button class="nav-link" id="nav-disabled-tab" data-bs-toggle="tab" data-bs-target="#nav-disabled"
              type="button" role="tab" aria-controls="nav-disabled" aria-selected="false" disabled>Disabled</button>
            <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home"
              type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
          </div>
        </nav>
      </div>
      <div class="card-body">
        <div class="tab-content text-dark" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">

            <form class="form-horizontal">

              <div class="row mb-3">
                <label for="inputName" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName" placeholder="{{ user.username| safe| lower }}"
                    readonly>
                </div>
              </div>

              <div class="row mb-3">
                <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName"
                    placeholder="{{ user.get_full_name| safe| capfirst }}">
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail" placeholder="{{ user.email| safe| lower }}"
                    readonly>
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputName2" class="col-sm-2 col-form-label">Is Superuser</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName2" placeholder="{{ user.is_superuser| safe }}"
                    readonly>
                </div>
              </div>
              <div class="row mb-3">
                <label for="lastLogin" class="col-sm-2 col-form-label">Last Login</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName2"
                    placeholder="{{ user.last_login| naturaltime }}" readonly>
                </div>
              </div>
              <div class="row mb-3">
                <label for="dateJoined" class="col-sm-2 col-form-label">Date joined</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName2"
                    placeholder="{{ user.date_joined| naturaltime }}" readonly>
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputExperience" class="col-sm-2 col-form-label">Experience</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="inputExperience" placeholder="Experience"></textarea>
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputSkills" class="col-sm-2 col-form-label">User Groups</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputSkills" placeholder="{{ user.groups }}">
                </div>
              </div>
              <div class="row mb-3">
                <div class="offset-sm-2 col-sm-10">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"> I agree to the <a href="#">terms and conditions</a>
                    </label>
                  </div>
                </div>
              </div>
              <div class="row mb-3">
                <div class="offset-sm-2 col-sm-10">
                  <button type="submit" class="btn btn-danger">Submit</button>
                </div>
              </div>

            </form>

          </div>

          <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab" tabindex="0">
            <div class="row g-3">
              <div class="col-12">
                <label for="inputAddress" class="form-label">Address</label>
                <input type="text" class="form-control" id="inputAddress" placeholder="{{ user.address| safe }}">
              </div>
              <div class="col-12">
                <label for="inputAddress2" class="form-label">Address 2</label>
                <input type="text" class="form-control" id="inputAddress2" placeholder="{{ user.address_2| safe }}">
              </div>
              <div class="col-md-6">
                <label for="inputCity" class="form-label">City</label>
                <input type="text" class="form-control" id="inputCity" placeholder="{{ user.city| safe }}">
              </div>
              <div class="col-md-4">
                <label for="inputCity" class="form-label">State</label>
                <input type="text" class="form-control" id="inputState" placeholder="{{ user.state| safe }}">
              </div>
              <div class="col-md-4">
                <label for="inputCountry" class="form-label">Country</label>
                <input type="text" class="form-control" id="inputCountry" placeholder="{{ user.country| safe }}">
              </div>
              <div class="col-md-4">
                <label for="inputZip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="inputZip" placeholder="{{ user.zip| safe }}">
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="nav-disabled" role="tabpanel" aria-labelledby="nav-disabled-tab" tabindex="0">
          </div>
          <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab"
            tabindex="0">
            Home
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'dist/js/pages/home/profile.js' %}" type="application/javascript" defer></script>

{% endblock js %}